---
# defaults file for roles/homebrew

brew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts

brew_cask_apps:
  - docker
  - google-chrome
  - visual-studio-code
  - slack
  - virtualbox
  - vagrant

brew_packages:
  - git
  - git-lfs
  - github/gh/gh
  - hub
  - nmap
  - htop
  - ctop
  - openssl
  - ssh-copy-id
  - tree
  - wget
  - tmux
  - iproute2mac
  - jq
  - go
  - deno
  - vim
  - fish
  - rbenv
  - ruby-build
  - rbenv-gemset
  - dnsmasq
  - docker-compose
  - docker-machine
  - minikube
  - kompose
  - terraform
  - packer